### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#82]
When running paster --plugin=ckan user add frontend email=a@b.com password=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1` --config=/src/ckan/ckan.ini we get error:

Traceback (most recent call last):
  File "/home/co/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 734, in command
    self._load_config()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 96, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/vagrant/src/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 124, in load_all
    unload_all()
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 182, in unload_all
    unload(*reversed(_PLUGINS))
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 210, in unload
    plugins_update()
  File "/vagrant/src/ckan/ckan/plugins/core.py", line 116, in plugins_update
    environment.update_config()
  File "/vagrant/src/ckan/ckan/config/environment.py", line 254, in update_config
    ckan_host, port = ckan_host.split(':')
ValueError: too many values to unpack

Any suggestions?

**Comment by tbalaz** [comment]
We had typo in config file.

http://**:**data.gov.hr
